create table REVINFO (
    REV integer generated by default as identity,
    REVTSTMP bigint,
    primary key (REV)
);

CREATE TABLE USER_DETAILS_AUD (
    USER_ID INTEGER NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    REV INTEGER NOT NULL,
    REVTYPE INTEGER NOT NULL,
    PRIMARY KEY (USER_ID, REV)
);

